In [ ]:
%matplotlib inline

In [ ]:
import os

import glob
import difflib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd

from fuzzywuzzy import process, fuzz
from shapely.geometry import Point

In [ ]:
%reload_ext autoreload
from utils.cleanup_helpers import rename_and_retain_cols_for_all_dfs, import_all_dfs, add_fuzzy_matches_key_column, merge_dfs

In [28]:
%store -r constants_unique_countries constants_fuzzy_matches

In [29]:
cwd = os.getcwd()

In [30]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.expand_frame_repr', False)

# # List of the unique countries/countries of interest based on the Happiness datafiles
# unique_countries_df = pd.DataFrame({'Unique_Countries': constants_unique_countries})

In [31]:
## Matching fuzzy country matches from the unique countries list to the countries in the countries features for all df
def update_all_dfs_with_fuzzy_matches_key(dfs_dict, fuzzy_dict_ref):
    
    for year, df in dfs_dict.items():
        df = add_fuzzy_matches_key_column(df, fuzzy_dict_ref, 'fuzzy_matches_key')
        dfs_dict[year] = df
        
    return dfs_dict

In [32]:
## Cleaning wrong formatting in columns of interest

def convert_to_float(df):
    
    for column in df.columns:
        if column not in ['Country', 'fuzzy_matches_key']:
            df[column] = df[column].str.replace(',', '.').astype(float)
            
    return df

In [33]:
## Removing the observations with missing values

def drop_na_rows(dfs_dict):
    
    for year, df in dfs_dict.items():
        dfs_dict[year] = df.dropna(subset=['fuzzy_matches_key'])
        
    return dfs_dict

In [34]:
## locating duplicates within the all df dict 

def identify_duplicate_rows(dfs_dict):
    duplicates_dict = {}
    
    for year, df in dfs_dict.items():
        duplicates = df[df['fuzzy_matches_key'].duplicated(keep=False)]
        if not duplicates.empty:
            duplicates_dict[year] = duplicates
            
    return duplicates_dict

In [35]:
## For the found duplicated rows average between the 2 rows is calculated and then duplicated observations are dropped and replaced with the calculated averages

def average_and_remove_duplicates(dfs_dict):
    updated_dfs = {}
    
    for year, df in dfs_dict.items():
        while df['fuzzy_matches_key'].duplicated().any():

            duplicated_keys = df[df['fuzzy_matches_key'].duplicated(keep=False)]['fuzzy_matches_key'].unique()
            
            for key in duplicated_keys:
                dup_rows = df[df['fuzzy_matches_key'] == key]
                mean_values = dup_rows[['Score_' + str(year), 'GDP_PC_' + str(year), 'Corruption_' + str(year)]].mean()
                mean_values['Country'] = dup_rows['Country'].iloc[0]
                mean_values['fuzzy_matches_key'] = key
                df = df[df['fuzzy_matches_key'] != key]
                df = pd.concat([df, pd.DataFrame([mean_values])], ignore_index=True)
            
        updated_dfs[year] = df

    return updated_dfs

In [36]:
## Ranking of countries based on score

def rank_countries(dfs_dict):
    
    for year, df in dfs_dict.items():
        df[f'rank_{year}'] = df[f'Score_{year}'].rank(ascending=False).astype(int)
        
    return dfs_dict

In [37]:
## Merge all df from the dictionary on the unique countries list into one df

def merge_all_dfs(dfs_dict):
    merged_df = dfs_dict[list(dfs_dict.keys())[0]]
    
    for year, df in list(dfs_dict.items())[1:]:
        if 'Country' in df.columns:
            df = df.rename(columns={'Country': f'Country_{year}'})
        merged_df = merged_df.merge(df, on='fuzzy_matches_key', how='outer')
        
    return merged_df

In [38]:
## Renaming the new countries column

def clean_merged_df(merged_df):

    columns_to_keep = [col for col in merged_df.columns if not col.startswith('Country')]
    cleaned_df = merged_df[columns_to_keep]
    cleaned_df = cleaned_df.rename(columns={'fuzzy_matches_key': 'unique countries'})
    
    return cleaned_df

In [39]:
## Filling missing values for Namibia with average of the next 2 years 

def fill_missing_values_2015(df):

    df_filled = df.copy()
    
    mask = df_filled[['Score_2015', 'GDP_PC_2015', 'Corruption_2015']].isnull().all(axis=1)
    indices_with_nan = df_filled[mask].index

    for index in indices_with_nan:
        df_filled.loc[index, 'Score_2015'] = np.mean([df_filled.loc[index, 'Score_2016'], df_filled.loc[index, 'Score_2017']])
        df_filled.loc[index, 'GDP_PC_2015'] = np.mean([df_filled.loc[index, 'GDP_PC_2016'], df_filled.loc[index, 'GDP_PC_2017']])
        df_filled.loc[index, 'Corruption_2015'] = np.mean([df_filled.loc[index, 'Corruption_2016'], df_filled.loc[index, 'Corruption_2017']])
    
    return df_filled

In [40]:
## Reranking after filling the missing values

def rerank_2015_countries(df_filled):
    
    df_filled['rank_2015'] = df_filled['Score_2015'].rank(ascending=False).astype(int)
    
    return df_filled

In [41]:
## Filling missing values for Corruption

def fill_missing_values_other(df_filled):
    
    mask = df_filled.isnull().any(axis=1)
    df_filled.loc[mask] = df_filled.loc[mask].fillna(0)
    
    return df_filled

In [42]:
## Ratio between score and GDP weight/ GDP as proportion of the score

def GDP_per_score(df_filled):
    years = range(2015, 2023)
    new_cols = ['unique countries']
    
    for year in years:
        score_col = f'Score_{year}'
        gdp_col = f'GDP_PC_{year}'
        ratio_col = f'GDP_to_Score_{year}'
        
        df_filled[ratio_col] = df_filled[gdp_col]/df_filled[score_col]
        df_filled.replace([np.inf, -np.inf], np.nan, inplace=True)
        new_cols.extend([score_col, gdp_col, f'Corruption_{year}', f'rank_{year}', ratio_col])
        
    return df_filled[new_cols]

In [43]:
## Local folder where datafiles are stored
data_path = '\\data\\happiness_score_2015_2022'
path = cwd + data_path

## Years of interest
years = range(2015, 2023)

## Dict with the unique countries containing the name variants within the dataframes
fuzzy_dict_ref = constants_fuzzy_matches

dfs_dict = import_all_dfs(years, path)
dfs_dict = rename_and_retain_cols_for_all_dfs(dfs_dict)
dfs_dict = update_all_dfs_with_fuzzy_matches_key(dfs_dict, fuzzy_dict_ref)

dfs_dict[2022] = convert_to_float(dfs_dict[2022])
dfs_dict_cleaned = drop_na_rows(dfs_dict)

duplicated_rows_dict = identify_duplicate_rows(dfs_dict_cleaned)
updated_dfs = average_and_remove_duplicates(dfs_dict_cleaned)
dfs_dict_ranked = rank_countries(updated_dfs)

merged_dataframe = merge_all_dfs(dfs_dict_ranked)
cleaned_dataframe = clean_merged_df(merged_dataframe)

## Rearranging the columns of newly merged df, to start from the unique countries column and be sorted by year Score_2015, GDP_PC_2015, Corruption_2015, rank_2015, Score_2016...
cols = cleaned_dataframe.columns.tolist()
cols.insert(0, cols.pop(cols.index('unique countries')))

cleaned_dataframe = cleaned_dataframe[cols]
filled_dataframe_2015 = fill_missing_values_2015(cleaned_dataframe)

reranked_df = rerank_2015_countries(filled_dataframe_2015)
cleaned_df = fill_missing_values_other(reranked_df)
GDP_to_score_df = GDP_per_score(cleaned_df)

GDP_to_score_df

,unique countries,Score_2015,GDP_PC_2015,Corruption_2015,rank_2015,GDP_to_Score_2015,Score_2016,GDP_PC_2016,Corruption_2016,rank_2016,...,Score_2021,GDP_PC_2021,Corruption_2021,rank_2021,GDP_to_Score_2021,Score_2022,GDP_PC_2022,Corruption_2022,rank_2022,GDP_to_Score_2022
0,Switzerland,7.587,1.396510,0.419780,1,0.184066,7.5090,1.52733,0.41203,2,...,7.5710,1.566,0.4130,3,0.206842,7.512,2.026,0.4610,4,0.269702
1,Iceland,7.561,1.302320,0.141450,2,0.172242,7.5010,1.42666,0.14975,3,...,7.5540,1.482,0.1700,4,0.196187,7.557,1.936,0.1910,3,0.256186
2,Denmark,7.527,1.325480,0.483570,3,0.176097,7.5260,1.44178,0.44453,1,...,7.6200,1.502,0.4850,2,0.197113,7.636,1.953,0.5320,2,0.255762
3,Norway,7.522,1.459000,0.365030,4,0.193964,7.4980,1.57744,0.35776,4,...,7.3920,1.543,0.4270,6,0.208739,7.365,1.997,0.4740,8,0.271147
4,Canada,7.427,1.326290,0.329570,5,0.178577,7.4040,1.44015,0.31329,6,...,7.1030,1.447,0.3350,14,0.203717,7.025,1.886,0.3680,15,0.268470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,Benin,3.340,0.286650,0.080100,137,0.085823,3.4840,0.39499,0.06681,136,...,5.0450,0.507,0.1780,96,0.100496,4.623,0.932,0.2300,111,0.201601
134,Togo,2.839,0.208680,0.107310,138,0.073505,3.3030,0.28123,0.11587,138,...,4.1070,0.254,0.1070,128,0.061846,4.112,0.771,0.1320,128,0.187500
135,Cyprus,5.692,1.208095,0.102130,62,0.212244,5.6585,1.31499,0.10903,59,...,5.8795,1.377,0.1305,61,0.234204,5.844,1.815,0.1375,63,0.310575
136,Congo,4.253,0.339330,0.096555,118,0.079786,4.2540,0.41385,0.07914,114,...,5.3420,0.518,0.1240,82,0.096967,5.075,0.950,0.1460,96,0.187192
137,Namibia,4.574,0.948652,0.098563,104,0.207401,4.5740,0.93287,0.10398,102,...,4.5740,0.882,0.0590,119,0.192829,4.459,1.292,0.0710,118,0.289751

In [44]:
# GDP_to_score_df.to_excel("output_3.xlsx") ## extract to excel to check on the data merged

In [46]:
## Removing observations with countries that are missing from the GDP df

def remove_zero_rows(df): 
    
    df_clean = df.dropna()
    
    return df_clean

In [47]:
## Load of the GDP df containing only columns of interest - data from 2015 to 2028 
data_path ='\\data\\gdp_output.xlsx'
file_path = cwd + data_path
gdp_output_df = pd.read_excel(file_path, usecols = [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,16])
gdp_output_df

,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,alpha_dict_key
0,3953.611,4124.405,4525.8870,5257.714,5345.058,5268.239,6373.300,6457.2170,7058.8230,7315.6490,7721.1550,8154.9990,8585.6290,9061.091,Albania
1,4153.322,3918.941,4014.7070,4106.997,3953.402,3321.601,3659.709,4314.6570,4481.0050,4522.3410,4620.8210,4704.0040,4728.4600,4756.436,Algeria
2,14895.316,12772.868,14618.3270,11786.433,10054.023,8571.937,10616.947,13655.2000,13709.4900,13520.4000,13326.2040,13493.8990,13984.3850,14489.737,Argentina
3,3529.026,3524.000,3868.9060,4195.963,4596.861,4268.550,4679.460,6583.6100,8007.9500,8478.4500,8859.1900,9210.8000,9750.3380,10466.560,Armenia
4,51412.250,51813.644,55797.3830,56341.937,54266.751,53071.718,63896.297,65526.1180,64964.2820,64602.6670,66302.8320,67970.2010,70251.2000,72142.302,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,2581.907,2720.168,2957.8990,3216.254,3439.102,3548.892,3753.428,4086.5190,4475.5070,4924.7660,5396.1460,5888.9310,6403.5570,6961.651,Vietnam
126,1508.382,1083.887,905.1810,710.384,702.286,575.458,519.486,619.5500,573.1940,605.8730,699.6540,786.5950,825.5770,848.956,Yemen
127,1307.536,1250.324,1495.7510,1475.200,1268.121,956.832,1137.344,1423.7530,1423.0590,1488.9560,1563.1490,1646.4430,1734.2300,1829.939,Zambia
128,1425.466,1444.716,1481.2410,2523.249,1746.508,1769.565,2321.629,2087.6710,1851.7040,1618.4690,1666.2830,1663.3450,1533.7810,1566.851,Zimbabwe
129,1696.700,1442.995,1514.9475,1816.697,1702.683,1389.833,1565.358,1598.3285,1639.8515,1698.7695,1731.5195,1772.8485,1813.0045,1843.399,Congo

In [50]:
## Renaming the column alpha_dict_key to unique countries to do the merge on it

gdp_output_df = gdp_output_df.rename(columns = {"alpha_dict_key": "unique countries"})
merged_dfs = merge_dfs(GDP_to_score_df, gdp_output_df)
merged_dfs
removed_0s_df = remove_zero_rows(merged_dfs)

## Rearranging into correct year order

fixed_df = removed_0s_df.reset_index(drop=True)
fixed_df

## Check for empty rows
# nan_rows = removed_0s_df[removed_0s_df.isna().any(axis=1)]
# print(nan_rows)

,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,...,Score_2021,Score_2022,rank_2015,rank_2016,rank_2017,rank_2018,rank_2019,rank_2020,rank_2021,rank_2022
0,3953.611,4124.405,4525.8870,5257.714,5345.058,5268.239,6373.300,6457.2170,7058.8230,7315.6490,...,7.571,7.512,1,2,4,5,6,3,3,4
1,4153.322,3918.941,4014.7070,4106.997,3953.402,3321.601,3659.709,4314.6570,4481.0050,4522.3410,...,7.554,7.557,2,3,3,4,4,4,4,3
2,14895.316,12772.868,14618.3270,11786.433,10054.023,8571.937,10616.947,13655.2000,13709.4900,13520.4000,...,7.620,7.636,3,1,2,3,2,2,2,2
3,3529.026,3524.000,3868.9060,4195.963,4596.861,4268.550,4679.460,6583.6100,8007.9500,8478.4500,...,7.392,7.365,4,4,1,2,3,5,6,8
4,51412.250,51813.644,55797.3830,56341.937,54266.751,53071.718,63896.297,65526.1180,64964.2820,64602.6670,...,7.103,7.025,5,6,7,7,9,11,14,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,2581.907,2720.168,2957.8990,3216.254,3439.102,3548.892,3753.428,4086.5190,4475.5070,4924.7660,...,3.623,3.702,129,132,138,138,137,135,133,132
126,1508.382,1083.887,905.1810,710.384,702.286,575.458,519.486,619.5500,573.1940,605.8730,...,4.208,4.339,130,131,132,130,131,127,127,121
127,1307.536,1250.324,1495.7510,1475.200,1268.121,956.832,1137.344,1423.7530,1423.0590,1488.9560,...,4.355,4.251,131,127,127,122,122,120,122,123
128,1425.466,1444.716,1481.2410,2523.249,1746.508,1769.565,2321.629,2087.6710,1851.7040,1618.4690,...,4.984,4.891,132,134,135,129,111,98,98,105
129,1696.700,1442.995,1514.9475,1816.697,1702.683,1389.833,1565.358,1598.3285,1639.8515,1698.7695,...,5.306,5.235,133,124,119,100,95,83,84,87

In [25]:
## Calculating changes in the ratio between current and previous year

def GDP_ratio_change(fix_df):
    years = range(2015, 2029)  
    
    for year in years:
        if year > 2015:
            Y2Y_change = f'GDP_Y2Y_change_{year} - {year-1}'
            fix_df[Y2Y_change] = fix_df[year] - fix_df[year - 1]
    
    fix_df.replace([np.inf, -np.inf], np.nan, inplace=True)

    new_cols = ['unique countries']
    new_cols.extend([item for year in range(2015, 2023) for item in [f'Score_{year}', f'GDP_PC_{year}', f'Corruption_{year}', f'rank_{year}', f'GDP_to_Score_{year}']])
    new_cols.extend([year for year in years]) 
    new_cols.extend([f'GDP_Y2Y_change_{year} - {year-1}' for year in range(2016, 2029)])  
    
    return fix_df[new_cols]

In [26]:
## Temp of GDP_to_Score ratio change

def GDP_temp(df_delta_2):
    years = range(2015, 2023)
    new_cols = ['unique countries']
    
    for year in years:
        if year > 2015:
            score1_col = f'GDP_to_Score_{year}'
            score2_col = f'GDP_to_Score_{year-1}'
            temp_col = f'GDP2Score_temp_{year} - {year-1}'
            df_delta_2[temp_col] = (df_delta_2[score1_col]-df_delta_2[score2_col])/100
            
        df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)
        new_cols.extend([f'GDP2Score_temp_{year} - {year-1}' for year in range(2016, 2023)]) 
        
    return df_delta_2[new_cols]

In [66]:
gdp_delta = GDP_ratio_change(fixed_df)

## Median of Scores for each country 

gdp_delta["Med_score"] = gdp_delta[[col for col in gdp_delta.columns if str(col).startswith('Score_')]].median(axis=1)

## Median of the GDP to Score ratios 
gdp_delta["Med_GDP2score"] = gdp_delta[[col for col in gdp_delta.columns if str(col).startswith('GDP_to_Score_')]].median(axis=1)

## Calculating the weights of the rest of the factors 

gdp_delta["leftover"] = gdp_delta["Med_score"] -(gdp_delta["Med_score"]*gdp_delta["Med_GDP2score"]) 

## Calculating the avg GDP weight 

gdp_delta["Avg_GDP_weight"] = gdp_delta["Med_score"] - gdp_delta["leftover"]

## Subset do to the temp function (the main df became to long and hard to keep up with)

gdp_delta_2 = gdp_delta[['unique countries'] + [col for col in gdp_delta.columns if str(col).startswith('GDP_to_Score_')]]
gdp_delta_3 = GDP_temp(gdp_delta_2)

## Subset only with the GDP for years with available score

gdp_delta_3_subset = gdp_delta_3.iloc[:, 0:8]

## Median for the temp GDP_to_Score ratio change 

gdp_delta_3_subset["Med_GDPtemp"] = gdp_delta_3_subset[[col for col in gdp_delta_3_subset.columns if str(col).startswith('GDP2Score_temp_')]].median(axis=1)

## Calculating the weight factor which is to be applied on the GDP weight 
gdp_delta_3_subset["Med_GDPtemp_2"] = gdp_delta_3_subset["Med_GDPtemp"] + 1
gdp_delta_4_subset = gdp_delta_3_subset[['unique countries'] + [col for col in gdp_delta_3_subset.columns if str(col).startswith('Med_GDPtemp')]]

## Merging the bigger df with the subset

gdp_delta_merged = merge_dfs(gdp_delta, gdp_delta_4_subset)

C:\Users\user\AppData\Local\Temp\ipykernel_18756\4014551374.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdp_delta["Med_score"] = gdp_delta[[col for col in gdp_delta.columns if str(col).startswith('Score_')]].median(axis=1)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4014551374.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdp_delta["Med_GDP2score"] = gdp_delta[[col for col in gdp_delta.columns if str(col).startswith('GDP_to_Score_')]].median(axis=1)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4014551374.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdp_delta["leftover"] = gdp_delta["Med_score"] -(gdp_delta["Med_score"]*gdp_delta["Med_GDP2score"])
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4014551374.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdp_delta["Avg_GDP_weight"] = gdp_delta["Med_score"] - gdp_delta["leftover"]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2[temp_col] = (df_delta_2[score1_col]-df_delta_2[score2_col])/100
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2[temp_col] = (df_delta_2[score1_col]-df_delta_2[score2_col])/100
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2[temp_col] = (df_delta_2[score1_col]-df_delta_2[score2_col])/100
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2[temp_col] = (df_delta_2[score1_col]-df_delta_2[score2_col])/100
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2[temp_col] = (df_delta_2[score1_col]-df_delta_2[score2_col])/100
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2[temp_col] = (df_delta_2[score1_col]-df_delta_2[score2_col])/100
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2[temp_col] = (df_delta_2[score1_col]-df_delta_2[score2_col])/100
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4266865491.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_2.replace([np.inf, -np.inf], np.nan, inplace=True)

Index([          'unique countries',                'Med_GDPtemp',
                    'Med_GDPtemp_2',                         2015,
                               2016,                         2017,
                               2018,                         2019,
                               2020,                         2021,
                               2022,                         2023,
                               2024,                         2025,
                               2026,                         2027,
                               2028,             'Avg_GDP_weight',
                  'Corruption_2015',            'Corruption_2016',
                  'Corruption_2017',            'Corruption_2018',
                  'Corruption_2019',            'Corruption_2020',
                  'Corruption_2021',            'Corruption_2022',
                      'GDP_PC_2015',                'GDP_PC_2016',
                      'GDP_PC_2017',                'GDP_PC_2018',
                      'GDP_PC_2019',                'GDP_PC_2020',
                      'GDP_PC_2021',                'GDP_PC_2022',
       'GDP_Y2Y_change_2016 - 2015', 'GDP_Y2Y_change_2017 - 2016',
       'GDP_Y2Y_change_2018 - 2017', 'GDP_Y2Y_change_2019 - 2018',
       'GDP_Y2Y_change_2020 - 2019', 'GDP_Y2Y_change_2021 - 2020',
       'GDP_Y2Y_change_2022 - 2021', 'GDP_Y2Y_change_2023 - 2022',
       'GDP_Y2Y_change_2024 - 2023', 'GDP_Y2Y_change_2025 - 2024',
       'GDP_Y2Y_change_2026 - 2025', 'GDP_Y2Y_change_2027 - 2026',
       'GDP_Y2Y_change_2028 - 2027',          'GDP_to_Score_2015',
                'GDP_to_Score_2016',          'GDP_to_Score_2017',
                'GDP_to_Score_2018',          'GDP_to_Score_2019',
                'GDP_to_Score_2020',          'GDP_to_Score_2021',
                'GDP_to_Score_2022',              'Med_GDP2score',
                        'Med_score',                 'Score_2015',
                       'Score_2016',                 'Score_2017',
                       'Score_2018',                 'Score_2019',
                       'Score_2020',                 'Score_2021',
                       'Score_2022',                   'leftover',
                        'rank_2015',                  'rank_2016',
                        'rank_2017',                  'rank_2018',
                        'rank_2019',                  'rank_2020',
                        'rank_2021',                  'rank_2022'],
      dtype='object')

In [ ]:
## New subset to work on the direct GDP movement influence to the score

gdp_delta_5_subset = gdp_delta_merged[['unique countries'] + ['Avg_GDP_weight'] + [col for col in gdp_delta_3_subset.columns if str(col).startswith('Med_GDPtemp')]]
gdp_delta_5_subset

    unique countries  Avg_GDP_weight  Med_GDPtemp  Med_GDPtemp_2
0            Albania        1.492778     0.000054       1.000054
1            Algeria        1.404583     0.000071       1.000071
2          Argentina        1.415276     0.000055       1.000055
3            Armenia        1.523482     0.000053       1.000053
4          Australia        1.393950     0.000077       1.000077
..               ...             ...          ...            ...
125          Vietnam        0.477893     0.000096       1.000096
126            Yemen        0.267990     0.000045       1.000045
127           Zambia        0.377318    -0.000028       0.999972
128         Zimbabwe        0.345469     0.000076       1.000076
129            Congo        0.609109     0.000025       1.000025

[130 rows x 4 columns]

In [60]:
## Calculating new weight of the GDP into the score

def PV_weight(df_delta_3):
    years = range(2023, 2029)
    new_cols = ['unique countries']
    
    for year in years:
        previous_score_col = 'Avg_GDP_weight' 
        temp = 'Med_GDPtemp_2'
        weight_col = f'new_weight_{year}'
        
        df_delta_3[weight_col] = df_delta_3[previous_score_col]*df_delta_3[temp]
        df_delta_3.replace([np.inf, -np.inf], np.nan, inplace=True)
        new_cols.extend([f'new_weight_{year}' for year in range(2023, 2029)]) 
        
    return df_delta_3[new_cols]

In [61]:
## Calculating an unadjusted score - only containing the new weight 

def new_weight_2_score(df_delta_4):
    years = range(2023, 2029)
    new_cols = ['unique countries']
    
    for year in years:
        PV_weight = f'new_weight_{year}' 
        leftover_score = 'leftover'
        unadj_score = f'unadj_score_{year}'
        
        df_delta_4[unadj_score] = df_delta_4[PV_weight] + df_delta_4[leftover_score]
        df_delta_4.replace([np.inf, -np.inf], np.nan, inplace=True)
        new_cols.extend([f'unadj_score_{year}' for year in range(2023, 2029)]) 
        
    return df_delta_4[new_cols]

In [83]:
new_score_gdp_weight = PV_weight(gdp_delta_5_subset).iloc[:, 0:7]
gdp_delta_6_subset = gdp_delta_merged[['unique countries'] + ['leftover']]
gdp_new_weight_merged = merge_dfs(gdp_delta_6_subset, new_score_gdp_weight)
gdp_new_weight_1 = new_weight_2_score(gdp_new_weight_merged).iloc[:, 0:7]

C:\Users\user\AppData\Local\Temp\ipykernel_18756\331947051.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_3[weight_col] = df_delta_3[previous_score_col]*df_delta_3[temp]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\331947051.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_3.replace([np.inf, -np.inf], np.nan, inplace=True)

In [114]:
years = range(2021, 2029)
gdp_delta_merged_temp = gdp_delta_merged[['unique countries'] + [col for col in gdp_delta_merged.columns if str(col).startswith('GDP_Y2Y_change_')] + [year for year in years]]

In [88]:
## Calculating year to year change in GDP 

def change_gdp_Y2Y(df_delta_5):
    years = range(2021, 2029)
    new_cols = ['unique countries']
    
    for year in years:
        if year > 2021:
            GDP_change = f'GDP_Y2Y_change_{year} - {year-1}' 
            past_year = year - 1
            gdp_change = f'gpd_change_{year}' 
            
            df_delta_5[gdp_change] = df_delta_5[GDP_change]/df_delta_5[past_year]
            df_delta_5.replace([np.inf, -np.inf], np.nan, inplace=True)
        
    new_cols.extend([f'gpd_change_{year}' for year in range(2022, 2029)]) 
        
    return df_delta_5[new_cols]

In [89]:
## Calculating type of movement of the GDP - positive or negative compared to previous year

def gdp_mov(df_delta_5a):
    years = range(2022, 2029)
    new_cols = ['unique countries']
    
    for year in years:
        if year > 2022:
            GDP_change_curr = f'gpd_change_{year}' 
            GDP_change_past_year = f'gpd_change_{year - 1}'
            gdp_movement = f'gpd_movement_{year}'
            
            df_delta_5a[gdp_movement] = df_delta_5a[GDP_change_curr] - df_delta_5a[GDP_change_past_year]
            df_delta_5a.replace([np.inf, -np.inf], np.nan, inplace=True)
        
    new_cols.extend([f'gpd_movement_{year}' for year in range(2023, 2029)]) 
        
    return df_delta_5a[new_cols]

In [91]:
gdp_Y2Y_subset_b = change_gdp_Y2Y(gdp_delta_merged_temp)
gdp_Y2Y_subset_a = gdp_mov(gdp_Y2Y_subset_b)
different_cols = merge_dfs(gdp_Y2Y_subset_a,gdp_Y2Y_subset_b)
gdp_Y2Y_subset_merged["Med_score_change"] = gdp_Y2Y_subset_merged[[col for col in gdp_Y2Y_subset_merged.columns if str(col).startswith('gpd_change_')]].median(axis=1)

C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5[gdp_change] = df_delta_5[GDP_change]/df_delta_5[past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5[gdp_change] = df_delta_5[GDP_change]/df_delta_5[past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5[gdp_change] = df_delta_5[GDP_change]/df_delta_5[past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5[gdp_change] = df_delta_5[GDP_change]/df_delta_5[past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5[gdp_change] = df_delta_5[GDP_change]/df_delta_5[past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5[gdp_change] = df_delta_5[GDP_change]/df_delta_5[past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5[gdp_change] = df_delta_5[GDP_change]/df_delta_5[past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2356930245.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a[gdp_movement] = df_delta_5a[GDP_change_curr] - df_delta_5a[GDP_change_past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a[gdp_movement] = df_delta_5a[GDP_change_curr] - df_delta_5a[GDP_change_past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a[gdp_movement] = df_delta_5a[GDP_change_curr] - df_delta_5a[GDP_change_past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a[gdp_movement] = df_delta_5a[GDP_change_curr] - df_delta_5a[GDP_change_past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a[gdp_movement] = df_delta_5a[GDP_change_curr] - df_delta_5a[GDP_change_past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a[gdp_movement] = df_delta_5a[GDP_change_curr] - df_delta_5a[GDP_change_past_year]
C:\Users\user\AppData\Local\Temp\ipykernel_18756\4216782188.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_5a.replace([np.inf, -np.inf], np.nan, inplace=True)

,unique countries,gpd_change_2022,gpd_change_2023,gpd_change_2024,gpd_change_2025,gpd_change_2026,gpd_change_2027,gpd_change_2028,gpd_movement_2023,gpd_movement_2024,gpd_movement_2025,gpd_movement_2026,gpd_movement_2027,gpd_movement_2028,Med_score_change
0,Albania,0.013167,0.093168,0.036384,0.055430,0.056189,0.052806,0.055379,0.080001,-0.056784,0.019046,0.000759,-0.003383,0.002573,0.055379
1,Algeria,0.178962,0.038554,0.009225,0.021776,0.018002,0.005199,0.005917,-0.140408,-0.029329,0.012552,-0.003775,-0.012803,0.000718,0.018002
2,Argentina,0.286170,0.003976,-0.013793,-0.014363,0.012584,0.036349,0.036137,-0.282194,-0.017768,-0.000571,0.026947,0.023765,-0.000212,0.012584
3,Armenia,0.406917,0.216346,0.058754,0.044907,0.039689,0.058577,0.073456,-0.190570,-0.157592,-0.013847,-0.005218,0.018888,0.014879,0.058754
4,Australia,0.025507,-0.008574,-0.005566,0.026317,0.025148,0.033559,0.026919,-0.034082,0.003008,0.031884,-0.001169,0.008411,-0.006640,0.025507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,Vietnam,0.088743,0.095188,0.100382,0.095716,0.091322,0.087389,0.087154,0.006445,0.005194,-0.004665,-0.004395,-0.003933,-0.000235,0.091322
126,Yemen,0.192621,-0.074822,0.057012,0.154787,0.124263,0.049558,0.028318,-0.267443,0.131834,0.097774,-0.030524,-0.074705,-0.021240,0.057012
127,Zambia,0.251823,-0.000487,0.046307,0.049829,0.053286,0.053319,0.055188,-0.252310,0.046794,0.003522,0.003457,0.000033,0.001869,0.053286
128,Zimbabwe,-0.100773,-0.113029,-0.125957,0.029543,-0.001763,-0.077894,0.021561,-0.012256,-0.012928,0.155500,-0.031306,-0.076130,0.099455,-0.077894
129,Congo,0.021063,0.025979,0.035929,0.019279,0.023869,0.022651,0.016765,0.004916,0.009950,-0.016650,0.004590,-0.001218,-0.005886,0.022651

In [93]:
## Year to year change in scores

def change_score_Y2Y(df_delta_6):
    years = range(2015, 2023)
    new_cols = ['unique countries']
    
    for year in years:
        if year > 2015:
            score_1 = f'Score_{year}' 
            score_2 = f'Score_{year-1}' 
            score_change = f'score_change_{year} - {year-1}'
            
            df_delta_6[score_change] = df_delta_6[score_1] - df_delta_6[score_2]
            df_delta_6.replace([np.inf, -np.inf], np.nan, inplace=True)
            new_cols.append(score_change)
        
    return df_delta_6[new_cols]

In [94]:
score_change = change_score_Y2Y(gdp_delta_merged)
score_change["Med_index_change"] = score_change[[col for col in score_change.columns if str(col).startswith('score_change_')]].median(axis=1)
score_change["Med_index_change_2"] = score_change["Med_index_change"] + 1

score_change

C:\Users\user\AppData\Local\Temp\ipykernel_18756\2437545578.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  score_change["Med_index_change"] = score_change[[col for col in score_change.columns if str(col).startswith('score_change_')]].median(axis=1)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\2437545578.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  score_change["Med_index_change_2"] = score_change["Med_index_change"] + 1

,unique countries,score_change_2016 - 2015,score_change_2017 - 2016,score_change_2018 - 2017,score_change_2019 - 2018,score_change_2020 - 2019,score_change_2021 - 2020,score_change_2022 - 2021,Med_index_change,Med_index_change_2
0,Albania,-0.078,-0.015,-0.007,-0.007,0.0799,0.0111,-0.059,-0.0070,0.9930
1,Algeria,-0.060,0.003,-0.009,-0.001,0.0105,0.0495,0.003,0.0030,1.0030
2,Argentina,-0.001,-0.004,0.033,0.045,0.0456,-0.0256,0.016,0.0160,1.0160
3,Armenia,-0.024,0.039,0.057,-0.040,-0.0660,-0.0960,-0.027,-0.0270,0.9730
4,Australia,-0.023,-0.088,0.012,-0.050,-0.0459,-0.1291,-0.078,-0.0500,0.9500
...,...,...,...,...,...,...,...,...,...,...
125,Vietnam,-0.115,-0.317,-0.046,-0.072,0.2452,0.1468,0.079,-0.0460,0.9540
126,Yemen,0.014,-0.051,0.130,0.159,0.2326,0.0424,0.131,0.1300,1.1300
127,Zambia,0.096,0.173,0.365,0.049,0.0727,-0.0677,-0.104,0.0727,1.0727
128,Zimbabwe,-0.049,-0.100,0.457,0.570,0.4153,0.0347,-0.093,0.0347,1.0347
129,Congo,0.261,0.264,0.491,0.273,0.2893,0.0727,-0.071,0.2640,1.2640

In [115]:
new_score_to_be_adj = merge_dfs(gdp_new_weight_1,gdp_Y2Y_subset_a)
new_score_to_be_adj_2 = merge_dfs(new_score_to_be_adj, score_change)

In [104]:
## Adjusting of the score based on the movement of the GDP

def adj_score(df_delta_7):
    years = range(2023, 2029)
    new_cols = ['unique countries']
    
    for year in years:
        gdp_change_col = f'gpd_movement_{year}'
        score = f'unadj_score_{year}' 
        factor = 'Med_index_change_2' 
        score_adj = f'Score_{year}'
        mask = df_delta_7[gdp_change_col] > 0
        
        df_delta_7.loc[mask, score_adj] = df_delta_7[mask][score] / df_delta_7[mask][factor]
        df_delta_7.loc[~mask, score_adj] = df_delta_7[~mask][score] * df_delta_7[~mask][factor]
        df_delta_7.replace([np.inf, -np.inf], np.nan, inplace=True)
        new_cols.append(score_adj)
        
    return df_delta_7[new_cols]

In [105]:
## Ranking of the new scores

def new_score_ranking(df_delta_8):
    years = range(2023, 2029)
    new_cols = ['unique countries']
    
    df_delta_8.replace([np.inf, -np.inf], np.nan, inplace=True)
    
    for year in years:
        score_new = f'Score_{year}' 
        new_rank = f'Rank_{year}'
        
        df_delta_8[new_rank] = df_delta_8[score_new].rank(ascending=False, method='average')
        new_cols.append(new_rank)
        
    return df_delta_8[new_cols]

In [106]:
## Rearranging the columns

def rearrange_columns(df_delta_10):
    cols = ['unique countries']
    years = range(2023, 2029)

    for year in years:
        cols.extend([f'Score_{year}', f'Rank_{year}'])

    return df_delta_10[cols]

In [107]:
## Renaming the rank columns of 2015 - 2022

def rename_past_rank_columns(df_delta_11):
    years = range(2015, 2023)
    
    for year in years:
        df_delta_11 = df_delta_11.rename(columns={f'rank_{year}': f'Rank_{year}'})
                                       
    return df_delta_11

In [108]:
## Rearranging of old and new columns

def rearrange_columns_all(df_delta_12):
    cols = ['unique countries']
    years = range(2015, 2029)

    for year in years:
        if f'Score_{year}' in df_delta_12.columns:
            cols.append(f'Score_{year}')
        if f'Rank_{year}' in df_delta_12.columns:
            cols.append(f'Rank_{year}')

    return df_delta_12[cols]

In [109]:
## Removing descimals from new rank columns

def remove_rank_decimal(df_delta_13):
    years = range(2023, 2029)
    
    for year in years:
        rank_col = f'Rank_{year}'
        if rank_col in df_delta_13.columns:
            df_delta_13[rank_col] = df_delta_13[rank_col].astype('Int64') 
            
    return df_delta_13

In [116]:
new_score = adj_score(new_score_to_be_adj_2)

new_score_ranked = new_score_ranking(new_score)
new_ranked_score = merge_dfs(new_score_ranked, new_score)

past_scores_df = gdp_delta_merged[['unique countries'] + [col for col in gdp_delta_merged.columns if str(col).startswith('Score_')] + [col for col in gdp_delta_merged.columns if str(col).startswith('rank_')]]
all_scores_15_28 = merge_dfs(past_scores_df, new_ranked_score)

renamed_ranked_all = rename_past_rank_columns(all_scores_15_28)
all_scores_to_28 = rearrange_columns_all(renamed_ranked_all)
all_scores = remove_rank_decimal(all_scores_to_28) ## Final result df

C:\Users\user\AppData\Local\Temp\ipykernel_18756\76490091.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_8.replace([np.inf, -np.inf], np.nan, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_18756\76490091.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_8[new_rank] = df_delta_8[score_new].rank(ascending=False, method='average')
C:\Users\user\AppData\Local\Temp\ipykernel_18756\76490091.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_8[new_rank] = df_delta_8[score_new].rank(ascending=False, method='average')
C:\Users\user\AppData\Local\Temp\ipykernel_18756\76490091.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_8[new_rank] = df_delta_8[score_new].rank(ascending=False, method='average')
C:\Users\user\AppData\Local\Temp\ipykernel_18756\76490091.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_8[new_rank] = df_delta_8[score_new].rank(ascending=False, method='average')
C:\Users\user\AppData\Local\Temp\ipykernel_18756\76490091.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_8[new_rank] = df_delta_8[score_new].rank(ascending=False, method='average')
C:\Users\user\AppData\Local\Temp\ipykernel_18756\76490091.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_delta_8[new_rank] = df_delta_8[score_new].rank(ascending=False, method='average')

In [113]:
all_scores_subset = all_scores[['unique countries'] + [col for col in all_scores.columns if str(col).startswith('Score_')]]
all_scores_23_28 = all_scores_subset.iloc[:, list(range(1)) + list(range(-6, 0))]
all_scores_23_28

,unique countries,Score_2023,Score_2024,Score_2025,Score_2026,Score_2027,Score_2028
0,Albania,7.563526,7.458007,7.563526,7.563526,7.458007,7.563526
1,Algeria,7.526863,7.526863,7.481904,7.526863,7.526863,7.481904
2,Argentina,7.698819,7.698819,7.698819,7.458246,7.458246,7.698819
3,Armenia,7.307308,7.307308,7.307308,7.307308,7.718479,7.718479
4,Australia,6.932252,7.681165,7.681165,6.932252,7.681165,6.932252
...,...,...,...,...,...,...,...
125,Vietnam,3.720803,3.720803,3.386362,3.386362,3.386362,3.386362
126,Yemen,4.354468,3.410188,3.410188,4.354468,4.354468,4.354468
127,Zambia,4.586854,3.986194,3.986194,3.986194,3.986194,3.986194
128,Zimbabwe,4.396468,4.396468,4.106529,4.396468,4.396468,4.106529
129,Congo,3.803415,3.803415,6.076699,3.803415,6.076699,6.076699

In [ ]:
constant_all_scores_23_28 = all_scores_23_28.copy()

In [ ]:
%store constant_all_scores_23_28