In [64]:
%matplotlib inline

In [814]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os

In [238]:
## Work file to achieve the unique countries list

In [192]:
reference_countries = ["Afghanistan","Albania","Algeria","Angola","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahrain","Bangladesh","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo","Costa Rica","Croatia","Cyprus","Czechia","Denmark","Djibouti","Dominican Republic","Ecuador","Egypt","El Salvador","Estonia","Ethiopia","Finland","France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Guatemala","Guinea","Haiti","Honduras","Hong Kong S.A","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Ivory Coast","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kosovo","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Lithuania","Luxembourg","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Mauritania","Mauritius","Mexico","Moldova","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Cyprus","North Macedonia","Northern Cyprus","Norway","Oman","Pakistan","Palestin","Panama","Paraguay","Peru","Philippines","Poland","Portugal","Puerto Rico","Qatar","Romania","Russia","Rwanda","Saudi Arabia","Senegal","Serbia","Sierra Leone","Singapore","Slovakia","Slovenia","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Taiwan","Tajikistan","Tanzania","Thailand","Togo","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States","Uruguay","Uzbekistan","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"]

In [193]:
## Trying to locate how many times each country is present through the years

column_values = countries_through_years[
    ['Country_2015', 'Country_2016', 'Country_2017', 'Country_2018', 'Country_2019', 'Country_2020', 'Country_2021', 'Country_2022']
].values
flat_values = column_values.flatten()
flat_values = flat_values.astype(str)
df2 = np.unique(flat_values)
df2 = pd.DataFrame(df2, columns=['Unique_Countries'])
columns_to_check = ['Country_2015', 'Country_2016', 'Country_2017', 'Country_2018', 'Country_2019', 'Country_2020', 'Country_2021', 'Country_2022']
for column in columns_to_check:
    new_column_name = f'In_{column}'
    df2[new_column_name] = df2['Unique_Countries'].isin(countries_through_years[column]).astype(int)
df2['Total'] = df2.sum(axis = 1)

              Unique_Countries  In_Country_2015  In_Country_2016  In_Country_2017  In_Country_2018  In_Country_2019  In_Country_2020  In_Country_2021  In_Country_2022  Total
0                  Afghanistan                1                1                1                1                1                1                1                1      8
1                      Albania                1                1                1                1                1                1                1                1      8
2                      Algeria                1                1                1                1                1                1                1                1      8
3                       Angola                1                1                1                1                0                0                0                0      4
4                    Argentina                1                1                1                1                1                1                1                1      8
5                      Armenia                1                1                1                1                1                1                1                1      8
6                    Australia                1                1                1                1                1                1                1                1      8
7                      Austria                1                1                1                1                1                1                1                1      8
8                   Azerbaijan                1                1                1                1                1                1                1                0      7
9                  Azerbaijan*                0                0                0                0                0                0                0                1      1
10                     Bahrain                1                1                1                1                1                1                1                1      8
11                  Bangladesh                1                1                1                1                1                1                1                1      8
12                     Belarus                1                1                1                1                1                1                1                0      7
13                    Belarus*                0                0                0                0                0                0                0                1      1
14                     Belgium                1                1                1                1                1                1                1                1      8
15                      Belize                0                1                1                1                0                0                0                0      3
16                       Benin                1                1                1                1                1                1                1                1      8
17                      Bhutan                1                1                1                1                1                0                0                0      5
18                     Bolivia                1                1                1                1                1                1                1                1      8
19      Bosnia and Herzegovina                1                1                1                1                1                1                1                1      8
20                    Botswana                1                1                1                1                1                1                1                0      7
21                   Botswana*                0                0                0                0                0                0                0                1      1
22                      Brazil                1                1                1                1                1                1                1                1      8
23                    Bulgaria                1                1                1                1                1                1                1                1      8
24                Burkina Faso                1                1                1                1                1                1                1                1      8
25                     Burundi                1                1                1                1                1                1                1                0      7
26                    Cambodia                1                1                1                1                1                1                1                1      8
27                    Cameroon                1                1                1                1                1                1                1                1      8
28                      Canada                1                1                1                1                1                1                1                1      8
29    Central African Republic                1                0                1                1                1                1                0                0      5
30                        Chad                1                1                1                1                1                1                1                0      7
31                       Chad*                0                0                0                0                0                0                0                1      1
32                       Chile                1                1                1                1                1                1                1                1      8
33                       China                1                1                1                1                1                1                1                1      8
34                    Colombia                1                1                1                1                1                1                1                1      8
35                     Comoros                1                1                0                0                1                1                1                0      5
36                    Comoros*                0                0                0                0                0                0                0                1      1
37                       Congo                0                0                0                0                0                0                0                1      1
38         Congo (Brazzaville)                1                1                1                1                1                1                1                0      7
39            Congo (Kinshasa)                1                1                1                1                1                1                0                0      6
40                  Costa Rica                1                1                1                1                1                1                1                1      8
41                     Croatia                1                1                1                1                1                1                1                1      8
42                      Cyprus                1                1                1                1                1                1                1                1      8
43              Czech Republic                1                1                1                1                1                1                1                0      7
44                     Czechia                0                0                0                0                0                0                0                1      1
45                     Denmark                1                1                1                1                1                1                1                1      8
46                    Djibouti                1                0                0                0                0                0                0                0      1
47          Dominican Republic                1                1                1                1                1                1                1                1      8
48                     Ecuador                1                1                1                1                1                1                1                1      8
49                       Egypt                1                1                1                1                1                1                1                1      8
50                 El Salvador                1                1                1                1                1                1                1                1      8
51                     Estonia                1                1                1                1                1                1                1                1      8
52       Eswatini, Kingdom of*                0                0                0                0                0                0                0                1      1
53                    Ethiopia                1                1                1                1                1                1                1                1      8
54                     Finland                1                1                1                1                1                1                1                1      8
55                      France                1                1                1                1                1                1                1                1      8
56                       Gabon                1                1                1                1                1                1                1                1      8
57                      Gambia                0                0                0                0                1                1                1                0      3
58                     Gambia*                0                0                0                0                0                0                0                1      1
59                     Georgia                1                1                1                1                1                1                1                1      8
60                     Germany                1                1                1                1                1                1                1                1      8
61                       Ghana                1                1                1                1                1                1                1                1      8
62                      Greece                1                1                1                1                1                1                1                1      8
63                   Guatemala                1                1                1                1                1                1                1                0      7
64                  Guatemala*                0                0                0                0                0                0                0                1      1
65                      Guinea                1                1                1                1                1                1                1                1      8
66                       Haiti                1                1                1                1                1                1                1                0      7
67                    Honduras                1                1                1                1                1                1                1                1      8
68                   Hong Kong                1                1                0                1                1                0                0                0      4
69   Hong Kong S.A.R. of China                0                0                0                0                0                1                1                1      3
70     Hong Kong S.A.R., China                0                0                1                0                0                0                0                0      1
71                     Hungary                1                1                1                1                1                1                1                1      8
72                     Iceland                1                1                1                1                1                1                1                1      8
73                       India                1                1                1                1                1                1                1                1      8
74                   Indonesia                1                1                1                1                1                1                1                1      8
75                        Iran                1                1                1                1                1                1                1                1      8
76                        Iraq                1                1                1                1                1                1                1                1      8
77                     Ireland                1                1                1                1                1                1                1                1      8
78                      Israel                1                1                1                1                1                1                1                1      8
79                       Italy                1                1                1                1                1                1                1                1      8
80                 Ivory Coast                1                1                1                1                1                1                1                1      8
81                     Jamaica                1                1                1                1                1                1                1                1      8
82                       Japan                1                1                1                1                1                1                1                1      8
83                      Jordan                1                1                1                1                1                1                1                1      8
84                  Kazakhstan                1                1                1                1                1                1                1                1      8
85                       Kenya                1                1                1                1                1                1                1                1      8
86                      Kosovo                1                1                1                1                1                1                1                1      8
87                      Kuwait                1                1                1                1                1                1                1                0      7
88                     Kuwait*                0                0                0                0                0                0                0                1      1
89                  Kyrgyzstan                1                1                1                1                1                1                1                1      8
90                        Laos                1                1                0                1                1                1                1                1      7
91                      Latvia                1                1                1                1                1                1                1                1      8
92                     Lebanon                1                1                1                1                1                1                1                1      8
93                     Lesotho                1                0                1                1                1                1                1                0      6
94                    Lesotho*                0                0                0                0                0                0                0                1      1
95                     Liberia                1                1                1                1                1                1                1                0      7
96                    Liberia*                0                0                0                0                0                0                0                1      1
97                       Libya                1                1                1                1                1                1                1                0      7
98                      Libya*                0                0                0                0                0                0                0                1      1
99                   Lithuania                1                1                1                1                1                1                1                1      8
100                 Luxembourg                1                1                1                1                1                1                1                0      7
101                Luxembourg*                0                0                0                0                0                0                0                1      1
102                  Macedonia                1                1                1                1                0                1                0                0      5
103                 Madagascar                1                1                1                1                1                1                1                0      7
104                Madagascar*                0                0                0                0                0                0                0                1      1
105                     Malawi                1                1                1                1                1                1                1                1      8
106                   Malaysia                1                1                1                1                1                1                1                1      8
107                   Maldives                0                0                0                0                0                1                1                0      2
108                       Mali                1                1                1                1                1                1                1                1      8
109                      Malta                1                1                1                1                1                1                1                1      8
110                 Mauritania                1                1                1                1                1                1                1                0      7
111                Mauritania*                0                0                0                0                0                0                0                1      1
112                  Mauritius                1                1                1                1                1                1                1                1      8

C:\Users\user\AppData\Local\Temp\ipykernel_26008\2397060510.py:12: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df2['Total'] = df2.sum(axis = 1)

In [195]:
df3['Unique_Countries'] = df3['Unique_Countries'].apply(lambda x: find_best_match(x, reference_countries))

In [189]:
df3.drop_duplicates(subset='Unique_Countries', inplace=True)

             Unique_Countries  In_Country_2015  In_Country_2016  In_Country_2017  In_Country_2018  In_Country_2019  In_Country_2020  In_Country_2021  In_Country_2022  Total
0                 Afghanistan                1                1                1                1                1                1                1                1      8
1                     Albania                1                1                1                1                1                1                1                1      8
2                     Algeria                1                1                1                1                1                1                1                1      8
3                      Angola                1                1                1                1                1                1                1                1      8
4                   Argentina                1                1                1                1                1                1                1                1      8
5                     Armenia                1                1                1                1                1                1                1                1      8
6                   Australia                1                1                1                1                1                1                1                1      8
7                     Austria                1                1                1                1                1                1                1                1      8
8                  Azerbaijan                1                1                1                1                1                1                1                1      8
10                    Bahrain                1                1                1                1                1                1                1                1      8
11                 Bangladesh                1                1                1                1                1                1                1                1      8
12                    Belarus                1                1                1                1                1                1                1                1      8
14                    Belgium                1                1                1                1                1                1                1                1      8
15                     Belize                1                1                1                1                1                1                1                1      8
16                      Benin                1                1                1                1                1                1                1                1      8
17                     Bhutan                1                1                1                1                1                1                1                1      8
18                    Bolivia                1                1                1                1                1                1                1                1      8
19     Bosnia and Herzegovina                1                1                1                1                1                1                1                1      8
20                   Botswana                1                1                1                1                1                1                1                1      8
22                     Brazil                1                1                1                1                1                1                1                1      8
23                   Bulgaria                1                1                1                1                1                1                1                1      8
24               Burkina Faso                1                1                1                1                1                1                1                1      8
25                    Burundi                1                1                1                1                1                1                1                0      7
26                   Cambodia                1                1                1                1                1                1                1                1      8
27                   Cameroon                1                1                1                1                1                1                1                1      8
28                     Canada                1                1                1                1                1                1                1                1      8
29   Central African Republic                1                1                1                1                1                1                1                1      8
30                       Chad                1                1                1                1                1                1                1                1      8
32                      Chile                1                1                1                1                1                1                1                1      8
33                      China                1                1                1                1                1                1                1                1      8
34                   Colombia                1                1                1                1                1                1                1                1      8
35                    Comoros                1                1                0                0                1                1                1                1      6
37                      Congo                1                1                1                1                1                1                1                1      8
40                 Costa Rica                1                1                1                1                1                1                1                1      8
41                    Croatia                1                1                1                1                1                1                1                1      8
42                     Cyprus                1                1                1                1                1                1                1                1      8
44                     Czechi                0                0                0                0                0                0                0                1      1
45                    Denmark                1                1                1                1                1                1                1                1      8
46                   Djibouti                1                0                0                0                0                0                0                0      1
47         Dominican Republic                1                1                1                1                1                1                1                1      8
48                    Ecuador                1                1                1                1                1                1                1                1      8
49                      Egypt                1                1                1                1                1                1                1                1      8
50                El Salvador                1                1                1                1                1                1                1                1      8
51                    Estonia                1                1                1                1                1                1                1                1      8
52             United Kingdom                1                1                1                1                1                1                1                1      8
53                   Ethiopia                1                1                1                1                1                1                1                1      8
54                    Finland                1                1                1                1                1                1                1                1      8
55                     France                1                1                1                1                1                1                1                1      8
56                      Gabon                1                1                1                1                1                1                1                1      8
57                     Gambia                1                1                1                1                1                1                1                1      8
59                    Georgia                1                1                1                1                1                1                1                1      8
60                    Germany                1                1                1                1                1                1                1                1      8
61                      Ghana                1                1                1                1                1                1                1                1      8
62                     Greece                1                1                1                1                1                1                1                1      8
63                  Guatemala                1                1                1                1                1                1                1                1      8
65                     Guinea                1                1                1                1                1                1                1                1      8
66                      Haiti                1                1                1                1                1                1                1                0      7
67                   Honduras                1                1                1                1                1                1                1                1      8
68              Hong Kong S.A                1                1                1                1                1                1                1                1      8
71                    Hungary                1                1                1                1                1                1                1                1      8
72                    Iceland                1                1                1                1                1                1                1                1      8
73                      India                1                1                1                1                1                1                1                1      8
74                  Indonesia                1                1                1                1                1                1                1                1      8
75                       Iran                1                1                1                1                1                1                1                1      8
76                       Iraq                1                1                1                1                1                1                1                1      8
77                    Ireland                1                1                1                1                1                1                1                1      8
78                     Israel                1                1                1                1                1                1                1                1      8
79                      Italy                1                1                1                1                1                1                1                1      8
80                Ivory Coast                1                1                1                1                1                1                1                1      8
81                    Jamaica                1                1                1                1                1                1                1                1      8
82                      Japan                1                1                1                1                1                1                1                1      8
83                     Jordan                1                1                1                1                1                1                1                1      8
84                 Kazakhstan                1                1                1                1                1                1                1                1      8
85                      Kenya                1                1                1                1                1                1                1                1      8
86                     Kosovo                1                1                1                1                1                1                1                1      8
87                     Kuwait                1                1                1                1                1                1                1                1      8
89                 Kyrgyzstan                1                1                1                1                1                1                1                1      8
90                       Laos                1                1                0                1                1                1                1                1      7
91                     Latvia                1                1                1                1                1                1                1                1      8
92                    Lebanon                1                1                1                1                1                1                1                1      8
93                    Lesotho                1                0                1                1                1                1                1                1      7
95                    Liberia                1                1                1                1                1                1                1                1      8
97                      Libya                1                1                1                1                1                1                1                1      8
99                  Lithuania                1                1                1                1                1                1                1                1      8
100                Luxembourg                1                1                1                1                1                1                1                1      8
102                 Macedonia                1                1                1                1                1                1                1                1      8
103                Madagascar                1                1                1                1                1                1                1                1      8
105                    Malawi                1                1                1                1                1                1                1                1      8
106                  Malaysia                1                1                1                1                1                1                1                1      8
107                  Maldives                1                1                1                1                1                1                1                1      8
108                      Mali                1                1                1                1                1                1                1                1      8
109                     Malta                1                1                1                1                1                1                1                1      8
110                Mauritania                1                1                1                1                1                1                1                1      8
112                 Mauritius                1                1                1                1                1                1                1                1      8
113                    Mexico                1                1                1                1                1                1                1                1      8
114                   Moldova                1                1                1                1                1                1                1                1      8
115                  Mongolia                1                1                1                1                1                1                1                1      8
116                Montenegro                1                1                1                1                1                1                1                1      8
117                   Morocco                1                1                1                1                1                1                1                1      8
118                Mozambique                1                0                1                1                1                1                1                1      7
119                   Myanmar                1                1                1                1                1                1                1                1      8
120                   Namibia                1                1                1                1                1                1                1                1      8
121                     Nepal                1                1                1                1                1                1                1                1      8
122               Netherlands                1                1                1                1                1                1                1                1      8
123               New Zealand                1                1                1                1                1                1                1                1      8
124                 Nicaragua                1                1                1                1                1                1                1                1      8
125                     Niger                1                1                1                1                1                1                1                1      8
127                   Nigeria                1                1                1                1                1                1                1                1      8
128              North Cyprus                1                1                1                1                1                1                1                1      8
130           North Macedonia                1                1                1                1                1                1                1                1      8
131           Northern Cyprus                1                1                1                1                1                1                1                1      8
132                    Norway                1                1                1                1                1                1                1                1      8
133                      Oman                1                0                0                0                0                0                0                0      1
134                  Pakistan                1                1                1                1                1                1                1                1      8

In [196]:
## Function to find the fuzzy matches

def find_match_ratio(name1, name2):
    return fuzz.ratio(name1, name2)

In [203]:
columns_to_check = ['Country_2015', 'Country_2016', 'Country_2017', 'Country_2018', 'Country_2019', 'Country_2020', 'Country_2021', 'Country_2022']

## Appling the fuzzy matching to find how many times each country is present through the years (to be noted the ratio is too small therefore it gave false matches but it was the basis of how to modify the fuzzy match function so that it matches the countries correctly)

for column in columns_to_check:
    new_column_name = f'In_{column}'
    df3[new_column_name] = df3['Unique_Countries'].apply(lambda x: 1 if any(find_match_ratio(x, name) > 65 for name in countries_through_years[column].dropna()) else 0)

df3.pop('Total')
df3['Total'] = df3.sum(axis = 1)

C:\Users\user\AppData\Local\Temp\ipykernel_26008\2675290411.py:8: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df3['Total'] = df3.sum(axis = 1)

             Unique_Countries  In_Country_2015  In_Country_2016  In_Country_2017  In_Country_2018  In_Country_2019  In_Country_2020  In_Country_2021  In_Country_2022  Total
0                 Afghanistan                1                1                1                1                1                1                1                1      8
1                     Albania                1                1                1                1                1                1                1                1      8
2                     Algeria                1                1                1                1                1                1                1                1      8
3                      Angola                1                1                1                1                1                1                1                1      8
4                   Argentina                1                1                1                1                1                1                1                1      8
5                     Armenia                1                1                1                1                1                1                1                1      8
6                   Australia                1                1                1                1                1                1                1                1      8
7                     Austria                1                1                1                1                1                1                1                1      8
8                  Azerbaijan                1                1                1                1                1                1                1                1      8
10                    Bahrain                1                1                1                1                1                1                1                1      8
11                 Bangladesh                1                1                1                1                1                1                1                1      8
12                    Belarus                1                1                1                1                1                1                1                1      8
14                    Belgium                1                1                1                1                1                1                1                1      8
16                      Benin                1                1                1                1                1                1                1                1      8
18                    Bolivia                1                1                1                1                1                1                1                1      8
19     Bosnia and Herzegovina                1                1                1                1                1                1                1                1      8
20                   Botswana                1                1                1                1                1                1                1                1      8
22                     Brazil                1                1                1                1                1                1                1                1      8
23                   Bulgaria                1                1                1                1                1                1                1                1      8
24               Burkina Faso                1                1                1                1                1                1                1                1      8
26                   Cambodia                1                1                1                1                1                1                1                1      8
27                   Cameroon                1                1                1                1                1                1                1                1      8
28                     Canada                1                1                1                1                1                1                1                1      8
29   Central African Republic                1                1                1                1                1                1                1                1      8
30                       Chad                1                1                1                1                1                1                1                1      8
32                      Chile                1                1                1                1                1                1                1                1      8
33                      China                1                1                1                1                1                1                1                1      8
34                   Colombia                1                1                1                1                1                1                1                1      8
37                      Congo                1                1                1                1                1                1                1                1      8
40                 Costa Rica                1                1                1                1                1                1                1                1      8
41                    Croatia                1                1                1                1                1                1                1                1      8
42                     Cyprus                1                1                1                1                1                1                1                1      8
44                    Czechia                1                1                1                1                1                1                1                1      8
45                    Denmark                1                1                1                1                1                1                1                1      8
47         Dominican Republic                1                1                1                1                1                1                1                1      8
48                    Ecuador                1                1                1                1                1                1                1                1      8
49                      Egypt                1                1                1                1                1                1                1                1      8
50                El Salvador                1                1                1                1                1                1                1                1      8
51                    Estonia                1                1                1                1                1                1                1                1      8
52             United Kingdom                1                1                1                1                1                1                1                1      8
53                   Ethiopia                1                1                1                1                1                1                1                1      8
54                    Finland                1                1                1                1                1                1                1                1      8
55                     France                1                1                1                1                1                1                1                1      8
56                      Gabon                1                1                1                1                1                1                1                1      8
57                     Gambia                1                1                1                1                1                1                1                1      8
59                    Georgia                1                1                1                1                1                1                1                1      8
60                    Germany                1                1                1                1                1                1                1                1      8
61                      Ghana                1                1                1                1                1                1                1                1      8
62                     Greece                1                1                1                1                1                1                1                1      8
63                  Guatemala                1                1                1                1                1                1                1                1      8
65                     Guinea                1                1                1                1                1                1                1                1      8
67                   Honduras                1                1                1                1                1                1                1                1      8
68              Hong Kong S.A                1                1                1                1                1                1                1                1      8
71                    Hungary                1                1                1                1                1                1                1                1      8
72                    Iceland                1                1                1                1                1                1                1                1      8
73                      India                1                1                1                1                1                1                1                1      8
74                  Indonesia                1                1                1                1                1                1                1                1      8
75                       Iran                1                1                1                1                1                1                1                1      8
76                       Iraq                1                1                1                1                1                1                1                1      8
77                    Ireland                1                1                1                1                1                1                1                1      8
78                     Israel                1                1                1                1                1                1                1                1      8
79                      Italy                1                1                1                1                1                1                1                1      8
80                Ivory Coast                1                1                1                1                1                1                1                1      8
81                    Jamaica                1                1                1                1                1                1                1                1      8
82                      Japan                1                1                1                1                1                1                1                1      8
83                     Jordan                1                1                1                1                1                1                1                1      8
84                 Kazakhstan                1                1                1                1                1                1                1                1      8
85                      Kenya                1                1                1                1                1                1                1                1      8
86                     Kosovo                1                1                1                1                1                1                1                1      8
87                     Kuwait                1                1                1                1                1                1                1                1      8
89                 Kyrgyzstan                1                1                1                1                1                1                1                1      8
91                     Latvia                1                1                1                1                1                1                1                1      8
92                    Lebanon                1                1                1                1                1                1                1                1      8
95                    Liberia                1                1                1                1                1                1                1                1      8
97                      Libya                1                1                1                1                1                1                1                1      8
99                  Lithuania                1                1                1                1                1                1                1                1      8
100                Luxembourg                1                1                1                1                1                1                1                1      8
102                 Macedonia                1                1                1                1                1                1                1                1      8
103                Madagascar                1                1                1                1                1                1                1                1      8
105                    Malawi                1                1                1                1                1                1                1                1      8
106                  Malaysia                1                1                1                1                1                1                1                1      8
107                  Maldives                1                1                1                1                1                1                1                1      8
108                      Mali                1                1                1                1                1                1                1                1      8
109                     Malta                1                1                1                1                1                1                1                1      8
110                Mauritania                1                1                1                1                1                1                1                1      8
112                 Mauritius                1                1                1                1                1                1                1                1      8
113                    Mexico                1                1                1                1                1                1                1                1      8
114                   Moldova                1                1                1                1                1                1                1                1      8
115                  Mongolia                1                1                1                1                1                1                1                1      8
116                Montenegro                1                1                1                1                1                1                1                1      8
117                   Morocco                1                1                1                1                1                1                1                1      8
119                   Myanmar                1                1                1                1                1                1                1                1      8
120                   Namibia                1                1                1                1                1                1                1                1      8
121                     Nepal                1                1                1                1                1                1                1                1      8
122               Netherlands                1                1                1                1                1                1                1                1      8
123               New Zealand                1                1                1                1                1                1                1                1      8
124                 Nicaragua                1                1                1                1                1                1                1                1      8
125                     Niger                1                1                1                1                1                1                1                1      8
127                   Nigeria                1                1                1                1                1                1                1                1      8
128              North Cyprus                1                1                1                1                1                1                1                1      8
130           North Macedonia                1                1                1                1                1                1                1                1      8
131           Northern Cyprus                1                1                1                1                1                1                1                1      8
132                    Norway                1                1                1                1                1                1                1                1      8
134                  Pakistan                1                1                1                1                1                1                1                1      8
137                    Panama                1                1                1                1                1                1                1                1      8
138                  Paraguay                1                1                1                1                1                1                1                1      8
139                      Peru                1                1                1                1                1                1                1                1      8
140               Philippines                1                1                1                1                1                1                1                1      8
141                    Poland                1                1                1                1                1                1                1                1      8
142                  Portugal                1                1                1                1                1                1                1                1      8
145                   Romania                1                1                1                1                1                1                1                1      8
146                    Russia                1                1                1                1                1                1                1                1      8
147                    Rwanda                1                1                1                1                1                1                1                1      8
149              Saudi Arabia                1                1                1                1                1                1                1                1      8

In [204]:
filtered_countries = df3[df3['Total'] >= 8]
filtered_countries.reset_index(drop=True, inplace=True)

             Unique_Countries  In_Country_2015  In_Country_2016  In_Country_2017  In_Country_2018  In_Country_2019  In_Country_2020  In_Country_2021  In_Country_2022  Total
0                 Afghanistan                1                1                1                1                1                1                1                1      8
1                     Albania                1                1                1                1                1                1                1                1      8
2                     Algeria                1                1                1                1                1                1                1                1      8
3                      Angola                1                1                1                1                1                1                1                1      8
4                   Argentina                1                1                1                1                1                1                1                1      8
5                     Armenia                1                1                1                1                1                1                1                1      8
6                   Australia                1                1                1                1                1                1                1                1      8
7                     Austria                1                1                1                1                1                1                1                1      8
8                  Azerbaijan                1                1                1                1                1                1                1                1      8
9                     Bahrain                1                1                1                1                1                1                1                1      8
10                 Bangladesh                1                1                1                1                1                1                1                1      8
11                    Belarus                1                1                1                1                1                1                1                1      8
12                    Belgium                1                1                1                1                1                1                1                1      8
13                      Benin                1                1                1                1                1                1                1                1      8
14                    Bolivia                1                1                1                1                1                1                1                1      8
15     Bosnia and Herzegovina                1                1                1                1                1                1                1                1      8
16                   Botswana                1                1                1                1                1                1                1                1      8
17                     Brazil                1                1                1                1                1                1                1                1      8
18                   Bulgaria                1                1                1                1                1                1                1                1      8
19               Burkina Faso                1                1                1                1                1                1                1                1      8
20                   Cambodia                1                1                1                1                1                1                1                1      8
21                   Cameroon                1                1                1                1                1                1                1                1      8
22                     Canada                1                1                1                1                1                1                1                1      8
23   Central African Republic                1                1                1                1                1                1                1                1      8
24                       Chad                1                1                1                1                1                1                1                1      8
25                      Chile                1                1                1                1                1                1                1                1      8
26                      China                1                1                1                1                1                1                1                1      8
27                   Colombia                1                1                1                1                1                1                1                1      8
28                      Congo                1                1                1                1                1                1                1                1      8
29                 Costa Rica                1                1                1                1                1                1                1                1      8
30                    Croatia                1                1                1                1                1                1                1                1      8
31                     Cyprus                1                1                1                1                1                1                1                1      8
32                    Czechia                1                1                1                1                1                1                1                1      8
33                    Denmark                1                1                1                1                1                1                1                1      8
34         Dominican Republic                1                1                1                1                1                1                1                1      8
35                    Ecuador                1                1                1                1                1                1                1                1      8
36                      Egypt                1                1                1                1                1                1                1                1      8
37                El Salvador                1                1                1                1                1                1                1                1      8
38                    Estonia                1                1                1                1                1                1                1                1      8
39             United Kingdom                1                1                1                1                1                1                1                1      8
40                   Ethiopia                1                1                1                1                1                1                1                1      8
41                    Finland                1                1                1                1                1                1                1                1      8
42                     France                1                1                1                1                1                1                1                1      8
43                      Gabon                1                1                1                1                1                1                1                1      8
44                     Gambia                1                1                1                1                1                1                1                1      8
45                    Georgia                1                1                1                1                1                1                1                1      8
46                    Germany                1                1                1                1                1                1                1                1      8
47                      Ghana                1                1                1                1                1                1                1                1      8
48                     Greece                1                1                1                1                1                1                1                1      8
49                  Guatemala                1                1                1                1                1                1                1                1      8
50                     Guinea                1                1                1                1                1                1                1                1      8
51                   Honduras                1                1                1                1                1                1                1                1      8
52              Hong Kong S.A                1                1                1                1                1                1                1                1      8
53                    Hungary                1                1                1                1                1                1                1                1      8
54                    Iceland                1                1                1                1                1                1                1                1      8
55                      India                1                1                1                1                1                1                1                1      8
56                  Indonesia                1                1                1                1                1                1                1                1      8
57                       Iran                1                1                1                1                1                1                1                1      8
58                       Iraq                1                1                1                1                1                1                1                1      8
59                    Ireland                1                1                1                1                1                1                1                1      8
60                     Israel                1                1                1                1                1                1                1                1      8
61                      Italy                1                1                1                1                1                1                1                1      8
62                Ivory Coast                1                1                1                1                1                1                1                1      8
63                    Jamaica                1                1                1                1                1                1                1                1      8
64                      Japan                1                1                1                1                1                1                1                1      8
65                     Jordan                1                1                1                1                1                1                1                1      8
66                 Kazakhstan                1                1                1                1                1                1                1                1      8
67                      Kenya                1                1                1                1                1                1                1                1      8
68                     Kosovo                1                1                1                1                1                1                1                1      8
69                     Kuwait                1                1                1                1                1                1                1                1      8
70                 Kyrgyzstan                1                1                1                1                1                1                1                1      8
71                     Latvia                1                1                1                1                1                1                1                1      8
72                    Lebanon                1                1                1                1                1                1                1                1      8
73                    Liberia                1                1                1                1                1                1                1                1      8
74                      Libya                1                1                1                1                1                1                1                1      8
75                  Lithuania                1                1                1                1                1                1                1                1      8
76                 Luxembourg                1                1                1                1                1                1                1                1      8
77                  Macedonia                1                1                1                1                1                1                1                1      8
78                 Madagascar                1                1                1                1                1                1                1                1      8
79                     Malawi                1                1                1                1                1                1                1                1      8
80                   Malaysia                1                1                1                1                1                1                1                1      8
81                   Maldives                1                1                1                1                1                1                1                1      8
82                       Mali                1                1                1                1                1                1                1                1      8
83                      Malta                1                1                1                1                1                1                1                1      8
84                 Mauritania                1                1                1                1                1                1                1                1      8
85                  Mauritius                1                1                1                1                1                1                1                1      8
86                     Mexico                1                1                1                1                1                1                1                1      8
87                    Moldova                1                1                1                1                1                1                1                1      8
88                   Mongolia                1                1                1                1                1                1                1                1      8
89                 Montenegro                1                1                1                1                1                1                1                1      8
90                    Morocco                1                1                1                1                1                1                1                1      8
91                    Myanmar                1                1                1                1                1                1                1                1      8
92                    Namibia                1                1                1                1                1                1                1                1      8
93                      Nepal                1                1                1                1                1                1                1                1      8
94                Netherlands                1                1                1                1                1                1                1                1      8
95                New Zealand                1                1                1                1                1                1                1                1      8
96                  Nicaragua                1                1                1                1                1                1                1                1      8
97                      Niger                1                1                1                1                1                1                1                1      8
98                    Nigeria                1                1                1                1                1                1                1                1      8
99               North Cyprus                1                1                1                1                1                1                1                1      8
100           North Macedonia                1                1                1                1                1                1                1                1      8
101           Northern Cyprus                1                1                1                1                1                1                1                1      8
102                    Norway                1                1                1                1                1                1                1                1      8
103                  Pakistan                1                1                1                1                1                1                1                1      8
104                    Panama                1                1                1                1                1                1                1                1      8
105                  Paraguay                1                1                1                1                1                1                1                1      8
106                      Peru                1                1                1                1                1                1                1                1      8
107               Philippines                1                1                1                1                1                1                1                1      8
108                    Poland                1                1                1                1                1                1                1                1      8
109                  Portugal                1                1                1                1                1                1                1                1      8
110                   Romania                1                1                1                1                1                1                1                1      8
111                    Russia                1                1                1                1                1                1                1                1      8
112                    Rwanda                1                1                1                1                1                1                1                1      8
113              Saudi Arabia                1                1                1                1                1                1                1                1      8

In [232]:
merged_set = filtered_countries[["Unique_Countries"]].copy()
merged_set
merged_set.to_excel("output.xlsx")